GET https://localhost:1125/users

###

POST https://localhost:1125/users
Content-Type: application/json

###

DELETE https://localhost:1125/users

###

PATCH https://localhost:1125/users
Content-Type: application/json

###

GET https://localhost:1125/cards

// 5e1cc108e02e21d9ce8544e7
###

POST https://localhost:1125/cards
Content-Type: application/json

# {
# "userId": "5e1cc108e02e21d9ce8544e7",
# "sport": "test3",
# "name": "post",
# "type": "post",
# "location": "post",
# "player": "post",
# "team": "post",
# "manufacturer": "post"
# }

###

DELETE https://localhost:1125/cards

###

PATCH https//localhost:1125/cards
Content-Type: application/json