GET http://localhost:1125/users

###

POST http://localhost:1125/users
Content-Type: application/json

###

DELETE http://localhost:1125/users

###

PATCH http://localhost:1125/users
Content-Type: application/json